[tool.poetry]
package-mode = false
name = "streamlit-aggrid-examples"
version = "1.1.0"
description = ""
authors = ["Pablo Fonseca"]


[tool.poetry.dependencies]
python = ">=3.10"
streamlit-aggrid = ">=1.2.0"
streamlit-code-editor = "^0.1.12"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.120.4"
uvicorn = "^0.38.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
